# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: main
    hooks:
      - id: pymarkdown
        args:
          - --disable-rules
          - line-length
          - scan